language: node_js
node_js:
- 5.3
deploy:
  provider: heroku
  api_key:
    secure: Fx6was1TbKp+dWMDWa3lV7lTttDnMAHNXc6lky2//hjeK5vFwmySd5aYnVgtUrj7QzxTMDZebM6tSwAwA/GcZKTQpZF76L8i3dgwuBZI33unRemBOe7UasssPe8+fIlofF0Bs2ipCGeUXvdGBliz4UlSN7hN4Ms2I8eoXbwFG87lolmmTHxy759tHPruZIJHpbddL8okTyucrN+h9WZAo1ComsTK/hnoAHCeJ0fEsndDMaHLDCcF/CdM0d83hY+FbQo3Cr7c7YWXciNiNLdB5PWSQcglEEEyZzCFs9M3uOGo04kwkmQIfuhJr9TqP2uYMTUtDAb4Z1uGfhTZMR1zf3jMp6nsDjc8fqZHLR7ZSAwKTThDVZk/CeqL1G65WgTmFxULzf8Ks8LK/6DeLtFMpz6/dM+mqlxFNrewpWCuutwCRSS0V8X8P32Hb3BzmyJWJatfgu9XlEb5xEFFSgW2UpI7/06UX+hVOp2PsLz3QQW0xpz5Qrbr/XmSqt4pXw9fbAQa5zSv0zLq4JmDlIwSMApBLdWaaQERMkUaWWdirGY276bRDT5C1eHjS9//OPhnp9Ar5YS3/IQt7UzsXIolMyOZUHb+mdjj1OLW0Lm50DtwvYBeJ/XvS1G60RrzYAY1AR0Wrw5rLIajlJy1ejseqh/CQmVF8SJAAN+z3Dn+I+M=
